wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1679086369.174705
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.9.7
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
act_fn:
  desc: null
  value: relu
act_func:
  desc: null
  value: tanh
optim_algo:
  desc: null
  value: nadam
weights_init:
  desc: null
  value: xavier_uniform
