wandb_version: 1

act_func:
  value: identity
batch_size:
  value: 64
l2_coeff:
  value: 0.5
loss_func:
  value: cross_ent
lr:
  value: 0.0001
n_epochs:
  value: 10
n_hidden:
  value: 5
n_hidden_units:
  value: 32
optim_algo:
  value: nag
relu_param:
  value: 0
weights_init:
  value: xavier_uniform
