wandb_version: 1

act_func:
  value: tanh
batch_size:
  value: 16
l2_coeff:
  value: 0.5
loss_func:
  value: mse
lr:
  value: 0.0001
n_epochs:
  value: 5
n_hidden:
  value: 3
n_hidden_units:
  value: 32
optim_algo:
  value: rmsprop
relu_param:
  value: 0
weights_init:
  value: xavier_uniform
