wandb_version: 1

act_func:
  value: identity
batch_size:
  value: 64
l2_coeff:
  value: 0.5
loss_func:
  value: mse
lr:
  value: 0.0001
n_epochs:
  value: 10
n_hidden:
  value: 3
n_hidden_units:
  value: 128
optim_algo:
  value: nadam
relu_param:
  value: 0.01
weights_init:
  value: xavier_uniform
