wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1679078822.048776
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.9.7
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
act_func:
  desc: null
  value: identity
batch_size:
  desc: null
  value: 64
l2_coeff:
  desc: null
  value: 0.0005
loss_func:
  desc: null
  value: cross_ent
lr:
  desc: null
  value: 0.0001
n_epochs:
  desc: null
  value: 5
n_hidden:
  desc: null
  value: 3
n_hidden_units:
  desc: null
  value: 128
optim_algo:
  desc: null
  value: nag
relu_param:
  desc: null
  value: 0
weights_init:
  desc: null
  value: xavier_uniform
