wandb_version: 1

act_func:
  value: tanh
batch_size:
  value: 16
l2_coeff:
  value: 0
loss_func:
  value: cross_ent
lr:
  value: 0.001
n_epochs:
  value: 5
n_hidden:
  value: 4
n_hidden_units:
  value: 32
optim_algo:
  value: nag
relu_param:
  value: 0.001
weight_init:
  value: random
