wandb_version: 1

act_func:
  value: sigmoid
batch_size:
  value: 16
l2_coeff:
  value: 0
loss_func:
  value: cross_ent
lr:
  value: 0.0001
n_epochs:
  value: 10
n_hidden:
  value: 3
n_hidden_units:
  value: 128
optim_algo:
  value: nadam
relu_param:
  value: 0.001
weight_init:
  value: random
