wandb_version: 1

act_func:
  value: relu
batch_size:
  value: 32
l2_coeff:
  value: 0.0005
loss_func:
  value: cross_ent
lr:
  value: 0.001
n_epochs:
  value: 5
n_hidden:
  value: 3
n_hidden_units:
  value: 128
optim_algo:
  value: sgd
relu_param:
  value: 0.1
weight_init:
  value: random
