wandb_version: 1

act_func:
  value: relu
batch_size:
  value: 64
l2_coeff:
  value: 0.5
loss_func:
  value: mse
lr:
  value: 0.0001
n_epochs:
  value: 10
n_hidden:
  value: 4
n_hidden_units:
  value: 64
optim_algo:
  value: sgdm
relu_param:
  value: 0.1
weight_init:
  value: random
