wandb_version: 1

act_func:
  value: relu
batch_size:
  value: 16
l2_coeff:
  value: 0
loss_func:
  value: mse
lr:
  value: 0.001
n_epochs:
  value: 10
n_hidden:
  value: 4
n_hidden_units:
  value: 32
optim_algo:
  value: rmsprop
relu_param:
  value: 0
weight_init:
  value: xavier_uniform
