wandb_version: 1

act_func:
  value: sigmoid
batch_size:
  value: 16
l2_coeff:
  value: 0.0005
loss_func:
  value: cross_ent
lr:
  value: 0.0001
n_epochs:
  value: 5
n_hidden:
  value: 4
n_hidden_units:
  value: 64
optim_algo:
  value: rmsprop
relu_param:
  value: 0.1
weight_init:
  value: xavier_uniform
