wandb_version: 1

act_func:
  value: identity
batch_size:
  value: 32
l2_coeff:
  value: 0
loss_func:
  value: cross_ent
lr:
  value: 0.001
n_epochs:
  value: 5
n_hidden:
  value: 5
n_hidden_units:
  value: 64
optim_algo:
  value: adam
relu_param:
  value: 0.1
weight_init:
  value: random
